### ISSUE TITLE
不是很懂python，登录遇到这个问题怎么破？

### ISSUE THREAD

**Issue by ycy1164656** [ly0/baidupcsapi#24]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/baidupcsapi/api.py", line 400, in __init__
    super(PCS, self).__init__(username, password, api_template, captcha_func=captcha_callback)
  File "/usr/local/lib/python2.7/site-packages/baidupcsapi/api.py", line 135, in __init__
    self._initiate()
  File "/usr/local/lib/python2.7/site-packages/baidupcsapi/api.py", line 181, in _initiate
    self._login()
  File "/usr/local/lib/python2.7/site-packages/baidupcsapi/api.py", line 278, in _login
    captcha = self._get_captcha(code_string)
  File "/usr/local/lib/python2.7/site-packages/baidupcsapi/api.py", line 221, in _get_captcha
    verifycode = self.captcha_func(jpeg)
  File "/usr/local/lib/python2.7/site-packages/baidupcsapi/api.py", line 227, in show_captcha
    import captcha
  File "/usr/local/lib/python2.7/site-packages/baidupcsapi/captcha.py", line 6, in <module>
    import Image
ImportError: No module named Image

**Comment by lilydjwg** [comment]
这里应该用 `from PIL import Image` 吧？

**Comment by ly0** [comment]
现在好像没有PIL依赖了吧?

**Comment by ycy1164656** [comment]
我Pip install image就ok了，缺少依赖库
