### ISSUE TITLE
在亚马逊EC2实例（Ubuntu）上操作出现错误

### ISSUE THREAD

**Issue by soiff** [ly0/baidupcsapi#52]
>>> pcs = PCS('account','password')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python2.7/site-packages/baidupcsapi/api.py", line 409, in __init__
    super(PCS, self).__init__(username, password, api_template, captcha_func=captcha_callback)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/baidupcsapi/api.py", line 135, in __init__
    self._initiate()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/baidupcsapi/api.py", line 190, in _initiate
    self._login()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/baidupcsapi/api.py", line 291, in _login
    self._check_account_exception(result.content)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/baidupcsapi/api.py", line 331, in _check_account_exception
    raise LoginFailed(msg)
baidupcsapi.api.LoginFailed: 请在弹出的窗口操作,或重新登录

**Comment by ly0** [comment]
这个应该是弹出一个用户验证框，试着在其他机器上登陆一下通过一下认证？

**Comment by soiff** [comment]
>>> pcs = PCS('account','password')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z0228/.local/lib/python2.7/site-packages/baidupcsapi/api.py", line 409, in __init__
    super(PCS, self).__init__(username, password, api_template, captcha_func=captcha_callback)
  File "/home/z0228/.local/lib/python2.7/site-packages/baidupcsapi/api.py", line 135, in __init__
    self._initiate()
  File "/home/z0228/.local/lib/python2.7/site-packages/baidupcsapi/api.py", line 190, in _initiate
    self._login()
  File "/home/z0228/.local/lib/python2.7/site-packages/baidupcsapi/api.py", line 291, in _login
    self._check_account_exception(result.content)
  File "/home/z0228/.local/lib/python2.7/site-packages/baidupcsapi/api.py", line 331, in _check_account_exception
    raise LoginFailed(msg)
baidupcsapi.api.LoginFailed: 请在弹出的窗口操作,或重新登录


在本机deepin系统中出现同样的错误

**Comment by ly0** [comment]
我是说在web界面上登陆一次通过一下安全认证？

**Comment by soiff** [comment]
我的EC2实例没有桌面环境，我也不准备安装桌面环境，感谢，已经有替代方案，问题关闭！

https://github.com/GangZhuo/BaiduPCS.git
