### ISSUE TITLE
验证码无效

### ISSUE THREAD

**Issue by howzanh** [ly0/baidupcsapi#58]
如图：
![image](https://user-images.githubusercontent.com/29419684/30246115-30099eb2-9623-11e7-8db5-160b83df3773.png)
是不是我操作有错。谢谢

**Comment by ly0** [comment]
有一定的可能性是编码问题，我确认一下

**Comment by howzanh** [comment]
好的，谢谢，
https://passport.baidu.com/cgi-bin/genimage?tcG6007c1e8e24cc132024a14564301d67f61ac430710057e4a
注意，这个地址产生验证码是变化的，非唯一。

**Comment by ly0** [comment]
刚刚在mac下试了一下并没有问题，所以我怀疑是windows编码问题，我这里没有环境测试，要不你print 一下请求试试

**Comment by howzanh** [comment]
![image](https://user-images.githubusercontent.com/29419684/30247542-99bc6288-9649-11e7-9cfc-3e11ccbdc673.png)

**Comment by howzanh** [comment]
print? 可以写代码我看下吗。

**Comment by ly0** [comment]
不对,感觉不大对头
你用的是哪个版本的?
当前版本不支持py2了而且验证码提示也不是这个

**Comment by howzanh** [comment]
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> from baidupcsapi import PCS
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from baidupcsapi import PCS
  File "C:\Users\dell\AppData\Local\Programs\Python\Python35\lib\site-packages\baidupcsapi\__init__.py", line 9, in <module>
    from .api import PCS
  File "C:\Users\dell\AppData\Local\Programs\Python\Python35\lib\site-packages\baidupcsapi\api.py", line 1068
    print '请求url', url
                ^
SyntaxError: Missing parentheses in call to 'print'
>>>

**Comment by howzanh** [comment]
baidupcsapi-0.3.8

**Comment by howzanh** [comment]
Finished processing dependencies for baidupcsapi==0.9.2 ，采用本地资源安装，执行 from baidupcsapi import PCS，错误如下。
-----------------------------------
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> from baidupcsapi import PCS
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from baidupcsapi import PCS
  File "C:\Users\dell\AppData\Local\Programs\Python\Python35\lib\site-packages\baidupcsapi\__init__.py", line 9, in <module>
    from .api import PCS
  File "C:\Users\dell\AppData\Local\Programs\Python\Python35\lib\site-packages\baidupcsapi\api.py", line 1068
    print '请求url', url
                ^
SyntaxError: Missing parentheses in call to 'print'
>>>

**Comment by ly0** [comment]
```print('请求url', url)```
